name: Latest Blog Posts
on:
  schedule:
    # Runs every hour
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "stjohngrimbly.com"
          commit_message: "Updated readme with the latest blog posts"
          feed_list: "https://stjohngrimbly.com/feed.xml"
